csv:
	csv2json -d data/direct-tax.csv > data/direct.json
	csv2json -d data/total.csv > data/total.json
	csv2json -d data/direct-tax-gdp-ratio.csv > data/gdp.json
	csv2json -d data/cost.csv > data/cost.json
	csv2json -d data/assessees.csv > data/assessees.json
	csv2json -d data/state.csv > data/state.json
