#!/usr/bin/env ruby

require 'roo'
require 'uri'
require 'pry'
require 'csv'

xls = Roo::Spreadsheet.open('./data/age.xls')
csv = CSV.open('./data/age.csv', 'w')
csv << ['state', 'age', 'male', 'female']
sheet = xls.sheet(0)

current_row_index = 8

while current_row_index <= 3715
  current_row = sheet.row(current_row_index)
  state_name = current_row[3].to_s
  state_name.sub!('State - ', '')
  state_name.sub!(/ \(\d+\)$/, '')
  state_name.downcase!
  state_name = state_name.split(' ').map(&:capitalize).join(' ')
  age = current_row[4].to_s
  age = Float(age).to_i rescue age
  unless age == 'All ages'
    csv << [state_name, age, current_row[6].to_i.to_s, current_row[7].to_i.to_s]
  end
  current_row_index += 1
end

csv.close
